### ISSUE TITLE
server HMR stops after error

### ISSUE THREAD

**Issue by Axxxx0n** [kimgysen/isomorphic-react-setup#2]
After you make reference error, HMR in server stops with `[HMR] You need to restart the application!`. How to recover HMR from error?

**Comment by kimgysen** [comment]
@Axxxx0n I didn't really think anybody looked at this repo lol. If you want you can always send me a Teams meeting invitation on kim.gysen@gmail.com after 6pm so I can help you track your problems as I'll gladly help you out. Probably I  need to upgrade this project as I made quite some upgrades over time in personal projects.
