### ISSUE TITLE
Error while including external package

### ISSUE THREAD

**Issue by dramoslance** [kimgysen/isomorphic-react-setup#5]
Hello.

Could you please tell me how to use a package that use the "window" object into this boilerplate?

I'm trying to use zoomus/websdk. But I'm getting "windos is undefined" error.

**Comment by kimgysen** [comment]
Hey I'm sorry for not replying earlier as I've been very busy. 
The problem with window is that this not available in NodeJS so I just shimmed this.  

You can just add a file: 

`global.window = global.window || {};`

And include this in your bundle. 
I'm not too happy with this but yes, some libs aren't built for SSR.

**Comment by kimgysen** [comment]
Let me know if you need more info or I can close this.

**Comment by dramoslance** [comment]
> Hey I'm sorry for not replying earlier as I've been very busy.
> The problem with window is that this not available in NodeJS so I just shimmed this.
> 
> You can just add a file:
> 
> `global.window = global.window || {};`
> 
> And include this in your bundle.
> I'm not too happy with this but yes, some libs aren't built for SSR.

Yes @kimgysen. I tried this solution but it did not work.

But I found an interesting resource within the Gatsby documentation. And I decided to solve it with the "Loadable" library + High Order Component to decide when to render the component.

[inside the HoC]
if(typeof window !== 'undefined')
// ...render the component that use the client library

Please let me share you the resource:
https://www.gatsbyjs.org/docs/using-client-side-only-packages/

**Comment by code-angels** [comment]
You may still run into problems when transpiling npm modules that use window before they're being interpreted at runtime. But if this works for your specific use case, go for it by all means.
